/** Preset car colors with hex codes for visual swatches */
export const PRESET_COLORS = [
  { name: "Black", hex: "#000000" },
  { name: "White", hex: "#FFFFFF" },
  { name: "Silver", hex: "#C0C0C0" },
  { name: "Gray", hex: "#808080" },
  { name: "Charcoal", hex: "#36454F" },
  { name: "Red", hex: "#DC2626" },
  { name: "Burgundy", hex: "#800020" },
  { name: "Blue", hex: "#2563EB" },
  { name: "Navy Blue", hex: "#000080" },
  { name: "Midnight Blue", hex: "#191970" },
  { name: "Sky Blue", hex: "#87CEEB" },
  { name: "Green", hex: "#16A34A" },
  { name: "Dark Green", hex: "#006400" },
  { name: "Olive", hex: "#808000" },
  { name: "Pearl White", hex: "#F5F5F0" },
  { name: "Champagne", hex: "#F7E7CE" },
  { name: "Gold", hex: "#FFD700" },
  { name: "Bronze", hex: "#CD7F32" },
  { name: "Brown", hex: "#8B4513" },
  { name: "Beige", hex: "#F5F5DC" },
  { name: "Orange", hex: "#EA580C" },
  { name: "Yellow", hex: "#EAB308" },
  { name: "Purple", hex: "#7C3AED" },
  { name: "Maroon", hex: "#800000" },
  { name: "Sand", hex: "#C2B280" },
  { name: "Titanium", hex: "#878681" },
  { name: "Graphite", hex: "#41424C" },
  { name: "Ice Blue", hex: "#D6ECEF" },
  { name: "Glacier White", hex: "#EEF0F2" },
  { name: "Magnetic Gray", hex: "#595959" },
];
